CREATE TABLE IF NOT EXISTS modules_translation (
	id text PRIMARY KEY,
	module_id text NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
	language text NOT NULL,
	title text NOT NULL,
	description text NOT NULL,
	topic_scope text NOT NULL,
	activities text[] NOT NULL DEFAULT '{}'::text[],
	grammar_focus text[] NOT NULL DEFAULT '{}'::text[],
	topic_scope_terms text[] NOT NULL DEFAULT '{}'::text[],
	UNIQUE (module_id, language)
);

INSERT INTO modules_translation (id, module_id, language, title, description, topic_scope, activities, grammar_focus, topic_scope_terms)
VALUES
	('mod-eng-vii-01-bi', 'mod-eng-vii-01', 'bahasa indonesia', 'Komunikasi kehidupan sehari-hari', 'Belajar memperkenalkan diri dan menggunakan bahasa Inggris dalam percakapan harian', 'ruang kelas, keluarga, teman, kelas, sapaan, respons, ungkapan sopan, perpisahan', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['pengalaman menyapa', 'kata ganti subjek', 'simple present tense', 'pertanyaan sederhana'], ARRAY['ruang kelas', 'keluarga', 'teman', 'kelas', 'sapaan', 'respons', 'ungkapan sopan', 'perpisahan']),
	('mod-eng-vii-02-bi', 'mod-eng-vii-02', 'bahasa indonesia', 'Ini tentang saya', 'Perkenalkan diri, keluarga, dan informasi pribadi', 'ruang kelas, identitas pribadi, anggota keluarga, informasi pribadi', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['mengenalkan diri', 'kata sifat kepemilikan', 'simple present', 'kata tanya'], ARRAY['ruang kelas', 'identitas pribadi', 'anggota keluarga', 'informasi pribadi']),
	('mod-eng-vii-03-bi', 'mod-eng-vii-03', 'bahasa indonesia', 'Jam berapa sekarang?', 'Berlatih menyebutkan waktu', 'ruang kelas, menyebut waktu, menanyakan waktu, ungkapan waktu, kegiatan harian', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['menyebut waktu', 'simple present tense', 'rutinitas harian', 'preposisi waktu'], ARRAY['ruang kelas', 'menyebut waktu', 'menanyakan waktu', 'ungkapan waktu', 'kegiatan harian']),
	('mod-eng-vii-04-bi', 'mod-eng-vii-04', 'bahasa indonesia', 'Inilah duniaku', 'Siswa mendeskripsikan lingkungan sekolah, kelas, perpustakaan, dan kantin menggunakan simple present tense dan bahasa deskriptif.', 'sekolah, kelas, perpustakaan, kantin, guru, siswa, buku, makanan, fasilitas, kehidupan sekolah sehari-hari', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'there is dan there are', 'kata ganti penunjuk', 'mendeskripsikan tempat'], ARRAY['sekolah', 'kelas', 'perpustakaan', 'kantin', 'guru', 'siswa', 'buku', 'makanan', 'fasilitas', 'kehidupan sekolah sehari-hari']),
	('mod-eng-vii-05-bi', 'mod-eng-vii-05', 'bahasa indonesia', 'Ini hari yang indah', 'Siswa berbicara tentang pengalaman harian mereka di sekolah, perpustakaan, dan kantin sambil mengekspresikan perasaan, pendapat, dan rutinitas.', 'lingkungan sekolah, kegiatan perpustakaan, kegiatan kantin, rutinitas harian, perasaan, cuaca, hari yang indah, teman, membaca, belajar', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'adjektiva', 'mengungkapkan perasaan', 'adverbia frekuensi'], ARRAY['lingkungan sekolah', 'kegiatan perpustakaan', 'kegiatan kantin', 'rutinitas harian', 'perasaan', 'cuaca', 'hari yang indah', 'teman', 'membaca', 'belajar']),
	('mod-eng-vii-06-bi', 'mod-eng-vii-06', 'bahasa indonesia', 'Kami menyukai apa yang kami lakukan', 'Siswa menjelaskan kegiatan yang mereka sukai di sekolah, perpustakaan, dan kantin, serta menjelaskan alasan kegiatan itu bermakna.', 'kegiatan sekolah, perpustakaan, kantin, hobi, minat, belajar, membaca, kegiatan kelompok, mata pelajaran favorit, preferensi pribadi', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'menyatakan suka dan preferensi', 'klausa sebab', 'kata ganti subjek dan objek'], ARRAY['kegiatan sekolah', 'perpustakaan', 'kantin', 'hobi', 'minat', 'belajar', 'membaca', 'kegiatan kelompok', 'mata pelajaran favorit', 'preferensi pribadi']),
	('mod-eng-vii-07-bi', 'mod-eng-vii-07', 'bahasa indonesia', 'Saya bangga pada Indonesia', 'Siswa mendeskripsikan Indonesia, rakyatnya, budayanya, dan prestasinya sambil mengekspresikan kebanggaan pada negara mereka.', 'Indonesia, identitas nasional, budaya, bahasa, sekolah, masyarakat, olahraga, prestasi, bendera, kebanggaan nasional', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'adjektiva', 'mengungkapkan kebanggaan', 'memberi alasan sederhana'], ARRAY['Indonesia', 'identitas nasional', 'budaya', 'bahasa', 'sekolah', 'masyarakat', 'olahraga', 'prestasi', 'bendera', 'kebanggaan nasional']),
	('mod-eng-vii-08-bi', 'mod-eng-vii-08', 'bahasa indonesia', 'Itulah yang seharusnya dilakukan teman', 'Siswa membahas persahabatan, kerja sama tim, dan sportivitas di lingkungan sekolah dan olahraga.', 'persahabatan, membantu orang lain, kerja sama tim, sekolah, sepak bola, bulu tangkis, bola basket, sportivitas, hormat, permainan yang adil', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['should', 'simple present tense', 'memberi nasihat', 'menunjukkan tanggung jawab'], ARRAY['persahabatan', 'membantu orang lain', 'kerja sama tim', 'sekolah', 'sepak bola', 'bulu tangkis', 'bola basket', 'sportivitas', 'hormat', 'permainan yang adil']),
	('mod-arab-vii-01-bi', 'mod-arab-vii-01', 'bahasa indonesia', 'Selamat pagi, apa kabar?', 'Berlatih memberi salam dengan ungkapan sopan', 'salam, respons salam, ungkapan sopan, informasi pribadi, kata ganti', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['pengalaman menyapa', 'kata ganti subjek', 'simple present tense', 'pertanyaan sederhana'], ARRAY['salam', 'respons salam', 'ungkapan sopan', 'informasi pribadi', 'kata ganti']),
	('mod-arab-vii-02-bi', 'mod-arab-vii-02', 'bahasa indonesia', 'Ini aku', 'Perkenalkan diri, keluarga, dan informasi pribadi', 'ruang kelas, identitas pribadi, anggota keluarga, informasi pribadi', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['mengenalkan diri', 'kata sifat kepemilikan', 'simple present', 'kata tanya'], ARRAY['ruang kelas', 'identitas pribadi', 'anggota keluarga', 'informasi pribadi']),
	('mod-arab-vii-03-bi', 'mod-arab-vii-03', 'bahasa indonesia', 'Jam berapa sekarang?', 'Berlatih menyebutkan waktu', 'ruang kelas, menyebut waktu, menanyakan waktu, ungkapan waktu, kegiatan harian', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['menyebut waktu', 'simple present tense', 'rutinitas harian', 'preposisi waktu'], ARRAY['ruang kelas', 'menyebut waktu', 'menanyakan waktu', 'ungkapan waktu', 'kegiatan harian']),
	('mod-arab-vii-04-bi', 'mod-arab-vii-04', 'bahasa indonesia', 'Inilah duniaku', 'Siswa mendeskripsikan lingkungan sekolah, kelas, perpustakaan, dan kantin menggunakan simple present tense dan bahasa deskriptif.', 'sekolah, kelas, perpustakaan, kantin, guru, siswa, buku, makanan, fasilitas, kehidupan sekolah sehari-hari', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'there is dan there are', 'kata ganti penunjuk', 'mendeskripsikan tempat'], ARRAY['sekolah', 'kelas', 'perpustakaan', 'kantin', 'guru', 'siswa', 'buku', 'makanan', 'fasilitas', 'kehidupan sekolah sehari-hari']),
	('mod-arab-vii-05-bi', 'mod-arab-vii-05', 'bahasa indonesia', 'Ini hari yang indah', 'Siswa berbicara tentang pengalaman harian mereka di sekolah, perpustakaan, dan kantin sambil mengekspresikan perasaan, pendapat, dan rutinitas.', 'lingkungan sekolah, kegiatan perpustakaan, kegiatan kantin, rutinitas harian, perasaan, cuaca, hari yang indah, teman, membaca, belajar', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'adjektiva', 'mengungkapkan perasaan', 'adverbia frekuensi'], ARRAY['lingkungan sekolah', 'kegiatan perpustakaan', 'kegiatan kantin', 'rutinitas harian', 'perasaan', 'cuaca', 'hari yang indah', 'teman', 'membaca', 'belajar']),
	('mod-arab-vii-06-bi', 'mod-arab-vii-06', 'bahasa indonesia', 'Kami menyukai apa yang kami lakukan', 'Siswa menjelaskan kegiatan yang mereka sukai di sekolah, perpustakaan, dan kantin, serta menjelaskan alasan kegiatan itu bermakna.', 'kegiatan sekolah, perpustakaan, kantin, hobi, minat, belajar, membaca, kegiatan kelompok, mata pelajaran favorit, preferensi pribadi', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'menyatakan suka dan preferensi', 'klausa sebab', 'kata ganti subjek dan objek'], ARRAY['kegiatan sekolah', 'perpustakaan', 'kantin', 'hobi', 'minat', 'belajar', 'membaca', 'kegiatan kelompok', 'mata pelajaran favorit', 'preferensi pribadi']),
	('mod-arab-vii-07-bi', 'mod-arab-vii-07', 'bahasa indonesia', 'Saya bangga pada Indonesia', 'Siswa mendeskripsikan Indonesia, rakyatnya, budayanya, dan prestasinya sambil mengekspresikan kebanggaan pada negara mereka.', 'Indonesia, identitas nasional, budaya, bahasa, sekolah, masyarakat, olahraga, prestasi, bendera, kebanggaan nasional', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['simple present tense', 'adjektiva', 'mengungkapkan kebanggaan', 'memberi alasan sederhana'], ARRAY['Indonesia', 'identitas nasional', 'budaya', 'bahasa', 'sekolah', 'masyarakat', 'olahraga', 'prestasi', 'bendera', 'kebanggaan nasional']),
	('mod-arab-vii-08-bi', 'mod-arab-vii-08', 'bahasa indonesia', 'Itulah yang seharusnya dilakukan teman', 'Siswa membahas persahabatan, kerja sama tim, dan sportivitas di lingkungan sekolah dan olahraga.', 'persahabatan, membantu orang lain, kerja sama tim, sekolah, sepak bola, bulu tangkis, bola basket, sportivitas, hormat, permainan yang adil', ARRAY['mendengarkan', 'berbicara', 'bertanya'], ARRAY['should', 'simple present tense', 'memberi nasihat', 'menunjukkan tanggung jawab'], ARRAY['persahabatan', 'membantu orang lain', 'kerja sama tim', 'sekolah', 'sepak bola', 'bulu tangkis', 'bola basket', 'sportivitas', 'hormat', 'permainan yang adil'])
ON CONFLICT (module_id, language) DO UPDATE SET
	title = EXCLUDED.title,
	description = EXCLUDED.description,
	topic_scope = EXCLUDED.topic_scope,
	activities = EXCLUDED.activities,
	grammar_focus = EXCLUDED.grammar_focus,
	topic_scope_terms = EXCLUDED.topic_scope_terms;
